# Generated by Django 5.0.7 on 2024-07-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursery_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.IntegerField(choices=[(1, 'flower'), (2, 'indoor'), (3, 'bonsai')], verbose_name='Category'),
        ),
    ]
